const loopCopy=[
  ["公开信号进入","姚欣已有 Booming Talk / AI LinkR 公开对谈入口。新的产品、市场或判断变化，先作为待核信号进入，而不是直接变成结论。"],
  ["事实校正","回到原音频，区分节目说明、本人原话和我们的分析，抽取三个半年后仍值得复访的判断。"],
  ["关系产品承接","如果需要理解判断变化，优先考虑 Talk；如果需要产业连接，再考虑 Hub。路由建议不替代产品 owner 的判断。"],
  ["发生第二次互动","复利的关键不是又发布一篇内容，而是带着上次留下的问题重新交流，并获得新的事实或关系位置。"],
  ["结果进入下一次判断","记录继续、调整或停止，并保留一个 owner 和下一步。半年后团队不需要从头认识这个人。"]
];
document.querySelectorAll("[data-loop]").forEach((b,i)=>b.onclick=()=>{document.querySelectorAll("[data-loop]").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelector("#loopDemo").innerHTML=`<span>姚欣 / PPIO · ${i+1}/5</span><h3>${loopCopy[i][0]}</h3><p>${loopCopy[i][1]}</p>`});
const C={"机构":"#f2c46d","人物":"#72c9ff","生态产品":"#b797e2","被投企业":"#63d7a6","公开方法":"#7aa8ff","投资主题":"#ee8fb2"};let D,rx=-.18,ry=.35,zoom=1,drag=false,lx=0,ly=0,pts=[];const cv=document.querySelector("#graphCanvas"),ctx=cv.getContext("2d"),detail=document.querySelector("#nodeDetail");
fetch("data.json").then(r=>r.json()).then(d=>{D=d;resize();draw()});function resize(){let r=cv.getBoundingClientRect(),d=devicePixelRatio||1;cv.width=r.width*d;cv.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)}addEventListener("resize",resize);
function draw(){requestAnimationFrame(draw);if(!D)return;let w=cv.clientWidth,h=cv.clientHeight,cx=w/2,cy=h/2;ctx.clearRect(0,0,w,h);let ns=D.nodes.map((n,i)=>{let a=i/13*Math.PI*2,r=90+i%5*37,x=Math.cos(a)*r,y=(i%7-3)*26,z=Math.sin(a)*r,x1=x*Math.cos(ry)-z*Math.sin(ry),z1=x*Math.sin(ry)+z*Math.cos(ry),y1=y*Math.cos(rx)-z1*Math.sin(rx),z2=y*Math.sin(rx)+z1*Math.cos(rx),p=430/(530+z2)*zoom;return{...n,sx:cx+x1*p,sy:cy+y1*p,sz:z2,rad:Math.max(3,7*p)}}).sort((a,b)=>a.sz-b.sz);pts=ns;D.edges.forEach(e=>{let a=ns.find(n=>n.id===e[0]),b=ns.find(n=>n.id===e[1]);if(!a||!b)return;ctx.strokeStyle=e[3]==="事实"?"#50627e88":"#9a765144";ctx.setLineDash(e[3]==="事实"?[]:[4,5]);ctx.beginPath();ctx.moveTo(a.sx,a.sy);ctx.lineTo(b.sx,b.sy);ctx.stroke()});ctx.setLineDash([]);ns.forEach(n=>{ctx.fillStyle=C[n.type]||"#aaa";ctx.globalAlpha=.8;ctx.beginPath();ctx.arc(n.sx,n.sy,n.rad,0,7);ctx.fill()});ctx.globalAlpha=1}
function show(n){detail.innerHTML=`<span>${n.type} / ${n.grade}</span><h3>${n.name}</h3><p>${n.summary}</p><p>${n.boundary||"事实边可由公开来源支撑；分析边不代表机构官方判断。"}</p>`}cv.onpointerdown=e=>{drag=true;lx=e.clientX;ly=e.clientY};cv.onpointermove=e=>{if(!drag)return;ry+=(e.clientX-lx)*.006;rx+=(e.clientY-ly)*.006;lx=e.clientX;ly=e.clientY};cv.onpointerup=e=>{drag=false;let r=cv.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,n=[...pts].reverse().find(n=>Math.hypot(n.sx-x,n.sy-y)<15);if(n)show(n)};cv.onwheel=e=>{e.preventDefault();zoom=Math.max(.55,Math.min(2,zoom*(e.deltaY>0?.92:1.08)))},{passive:false};
