const C={"机构":"#f2c46d","人物":"#72c9ff","生态产品":"#b797e2","被投企业":"#63d7a6","公开方法":"#7aa8ff","投资主题":"#ee8fb2"};
const demo=[["yao","公开信号","已有 Booming Talk / AI LinkR 对谈入口。先找出能在半年后复访的判断。"],["verify","证据核验","节目说明、本人原话、我们的分析必须分层；共现不等于关系。"],["talk","产品路由","优先路由到 Talk：围绕判断变化建立连续观察，而不是再做一次泛访谈。"],["outcome","下一步唯一动作","回听原音频，抽取 3 个半年后可复访判断，再决定是否值得第二次互动。"]];
let D,S,step=-1,route="Talk",rx=-.2,ry=.35,zoom=1,drag=false,lx=0,ly=0,pts=[];const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
fetch("data.json").then(r=>r.json()).then(d=>{D=d;S=D.nodes.find(n=>n.id==="yao");people();panel();resize();draw()});
function people(){let a=D.nodes.filter(n=>n.type==="人物");$("#people").innerHTML=a.map(n=>`<button class="person ${n.id===S.id?"active":""}" data-id="${n.id}"><strong>${esc(n.name)}</strong><small>${esc(n.grade)}</small><p>${esc(n.status||"待判断")} · ${esc(n.nextAction||"待补下一步")}</p></button>`).join("");document.querySelectorAll(".person").forEach(b=>b.onclick=()=>select(b.dataset.id))}
function panel(){let n=S;$("#workbench").innerHTML=`<span class="eyebrow">CURRENT DECISION</span><h2>${esc(n.name)}</h2><span class="status">${esc(n.grade)}</span><section><span>为什么现在看</span><p>${esc(n.summary)}</p></section><section><span>证据边界</span><p>${esc(n.boundary||"公开事实可引用；分析和待核不能当成机构结论。")}</p></section><section><span>选择关系动作</span><div class="route">${["Camp","Hub","Talk","一对一"].map(x=>`<button class="${x===route?"selected":""}" data-route="${x}">${x}</button>`).join("")}</div></section><section><span>下一步唯一动作</span><p class="next">${esc(n.nextAction||"先补一个能改变判断的公开事实。")}</p><p class="note">Owner：${esc(n.owner||"待蓝驰内部确认")} · 演示不会写入内部系统。</p></section>`;document.querySelectorAll("[data-route]").forEach(b=>b.onclick=()=>{route=b.dataset.route;panel()})}
function select(id){S=D.nodes.find(n=>n.id===id)||S;people();panel()}
function run(i){step=i;document.querySelectorAll("[data-step]").forEach((b,j)=>b.classList.toggle("active",j===i));let s=demo[i];select(s[0]);$("#decision").innerHTML=`<strong>${i+1}/4 · ${s[1]}</strong><p>${s[2]}</p>`;$("#startDemo").textContent=i<3?"下一步 →":"重新演示 ↺"}
$("#startDemo").onclick=()=>run(step<3?step+1:0);$("#steps").onclick=e=>{let b=e.target.closest("button");if(b)run(+b.dataset.step)};
const cv=$("#graph"),ctx=cv.getContext("2d");function resize(){let r=cv.getBoundingClientRect(),d=devicePixelRatio||1;cv.width=r.width*d;cv.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)}addEventListener("resize",resize);
function draw(){requestAnimationFrame(draw);if(!D)return;let w=cv.clientWidth,h=cv.clientHeight,cx=w/2,cy=h/2;ctx.clearRect(0,0,w,h);let ns=D.nodes.map((n,i)=>{let a=i/13*Math.PI*2,r=90+i%5*35,x=Math.cos(a)*r,y=(i%7-3)*24,z=Math.sin(a)*r,x1=x*Math.cos(ry)-z*Math.sin(ry),z1=x*Math.sin(ry)+z*Math.cos(ry),y1=y*Math.cos(rx)-z1*Math.sin(rx),z2=y*Math.sin(rx)+z1*Math.cos(rx),p=420/(520+z2)*zoom;return{...n,sx:cx+x1*p,sy:cy+y1*p,sz:z2,rad:Math.max(3,7*p)}}).sort((a,b)=>a.sz-b.sz);pts=ns;D.edges.forEach(e=>{let a=ns.find(n=>n.id===e[0]),b=ns.find(n=>n.id===e[1]);if(!a||!b)return;ctx.strokeStyle=e[3]==="事实"?"#50627e88":"#8a755f55";ctx.setLineDash(e[3]==="事实"?[]:[4,5]);ctx.beginPath();ctx.moveTo(a.sx,a.sy);ctx.lineTo(b.sx,b.sy);ctx.stroke()});ctx.setLineDash([]);ns.forEach(n=>{ctx.fillStyle=C[n.type]||"#aaa";ctx.globalAlpha=n.id===S.id?1:.72;ctx.beginPath();ctx.arc(n.sx,n.sy,n.id===S.id?n.rad+4:n.rad,0,7);ctx.fill();if(n.id===S.id){ctx.globalAlpha=1;ctx.fillStyle="#fff";ctx.font="12px sans-serif";ctx.fillText(n.name,n.sx+12,n.sy-10)}});ctx.globalAlpha=1}
cv.onpointerdown=e=>{drag=true;lx=e.clientX;ly=e.clientY};cv.onpointermove=e=>{if(!drag)return;ry+=(e.clientX-lx)*.006;rx+=(e.clientY-ly)*.006;lx=e.clientX;ly=e.clientY};cv.onpointerup=e=>{drag=false;let r=cv.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,n=[...pts].reverse().find(n=>Math.hypot(n.sx-x,n.sy-y)<14);if(n)select(n.id)};cv.onwheel=e=>{e.preventDefault();zoom=Math.max(.5,Math.min(2,zoom*(e.deltaY>0?.92:1.08)))},{passive:false};
